name: shopify
description: Unofficial Shopify plugin for Flutter
version: 0.0.1
repository: https://github.com/netsells/shopify-flutter
issue_tracker: https://github.com/netsells/shopify-flutter/issues
platforms:
  ios:
  android:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  netsells_flutter_analysis: ^1.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.netsells.shopify
        pluginClass: ShopifyPlugin
      ios:
        pluginClass: ShopifyPlugin
